<a href="https://colab.research.google.com/github/Rheilly/BSIS-2A/blob/main/Numphy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
array = np.array([1,2,3,4,5])

In [2]:
mean= np.mean(array)

In [3]:
print (mean)

3.0


In [16]:
median= np.median(array)

In [10]:
print(median)

3.0


In [17]:
max= np.max(array)

In [18]:
print (max)

5


In [19]:
stv_dev= np.std(array)

In [22]:
print(stv_dev)

1.4142135623730951


In [23]:
total= np.sum(array)

In [24]:
print(total)

15


In [34]:
reshaped_array= array.reshape((5,1))

In [26]:
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [35]:
array1= np.array([1,2,3])
array2= np.array([4,5,6])
concatenated=np.concatenate((array,array2))

In [28]:
print(concatenated)

[1 2 3 4 5 6]


In [29]:
numbers=np.linspace(0,10,5)

In [30]:
print(numbers)

[ 0.   2.5  5.   7.5 10. ]


In [31]:
range_array=np.arange(0,10,2)

In [33]:
print(range_array)

[0 2 4 6 8]
